# Generated by Django 5.1.3 on 2024-11-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("employee", "Employee")],
                default="employee",
                max_length=10,
            ),
        ),
    ]
