# Generated by Django 5.1.3 on 2024-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_pickup_remove_shift_unique_shift_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickup",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Request", "Request"),
                    ("Declined", "Declined"),
                ],
                max_length=10,
            ),
        ),
    ]
