# Generated by Django 5.1.3 on 2024-12-03 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_pickup_request_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                ("approval_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("Approved", "Approved"), ("Declined", "Declined")],
                        max_length=10,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.uniqueshift",
                    ),
                ),
            ],
        ),
    ]
