# Generated by Django 5.1.3 on 2024-12-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_approval"),
    ]

    operations = []
