# Generated by Django 5.1.3 on 2024-12-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20241202_2030"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="approval",
            name="unique_manager_employee",
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.UniqueConstraint(
                fields=("manager", "employee", "shift"),
                name="unique_manager_employee_shift",
            ),
        ),
    ]
